version: '3.8'

services:

  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    ports:
      - ${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/postgres
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # backend:
  #   depends_on:
  #     - postgresdb
  #   build: ./backend
  #   restart: unless-stopped
  #   env_file: ./backend/.env
  #   ports:
  #     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  #   environment:
  #     - DB_HOST=postgresdb
  #     - DB_USER=$POSTGRESDB_USER
  #     - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
  #     - DB_NAME=$POSTGRESDB_DATABASE
  #     - DB_PORT=$POSTGRESDB_DOCKER_PORT
  #   stdin_open: true
  #   tty: true

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always

volumes:
  db:
    driver: local
  redis-data:
    driver: local